

CC = @cl
LD = @link

CFLAGS = /nologo /W3 /MT /O2 /D "_MSVC" /c /EHsc
LDFLAGS = /nologo gdi32.lib user32.lib msimg32.lib winmm.lib
CCOUT = /Fo
LDOUT = /OUT: 


OBJS = 	ling.o \
	datafile.o \
	error.o \
	preload.o \
	game.o \
	script.o \
	action.o \
	render.o \
	map.o

	
TARGET = ../test.exe
SCRIPT_DEMO = ../demo.dll

all: $(TARGET) $(SCRIPT_DEMO) clean

$(TARGET): $(OBJS)
	@echo Linking $@ ...
	$(LD) $(OBJS) $(LDFLAGS) $(LDOUT)$@
	@echo --------------------------------------------
	@echo done.

$(SCRIPT_DEMO): script_demo.o
	@echo Linking SCRIPT_DEMO ...
	$(LD) $(LDFLAGS) script_demo.o $(LDOUT)$@ /DLL
	@echo --------------------------------------------
	
.cpp.o:
	@echo Compling $< ...
	$(CC) $< $(CFLAGS) $(CCOUT)$@ 
	@echo --------------------------------------------

.c.o:
	@echo Compling $< ...
	$(CC) $< $(CFLAGS) $(CCOUT)$@ 
	@echo --------------------------------------------



rebuild: clean $(TARGET)


.PHONY: clean

clean:
	del *.o


