

CC = @cl
LD = @link

CFLAGS = /nologo /W3 /MT /O2 /D "_MSVC" /c /EHsc
LDFLAGS = /nologo gdi32.lib user32.lib msimg32.lib winmm.lib
CCOUT = /Fo
LDOUT = /OUT: 


OBJS = 	ling.o \
	memory.o \
	datafile.o \
	error.o \
	preload.o

	
TARGET = test.exe

all: $(TARGET) 

$(TARGET): $(OBJS)
	@echo Linking $@ ...
	$(LD) $(OBJS) $(LDFLAGS) $(LDOUT)$@


.cpp.o:
	@echo Compling $< ...
	$(CC) $< $(CFLAGS) $(CCOUT)$@ 

rebuild: clean $(TARGET)


.PHONY: clean

clean:
	del *.o


